### ISSUE TITLE
Экономика должна быть экономной

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#10]
https://github.com/ks38/skillbox_python/blob/3e7752ba7b8284d98f0e047e112a0b40e64ba698/module_7/tasks/task_7.py#L24
Можно в цикле сэкономить:
https://izamorfix.ru/matematika/algebra/arif_prog_summa.html

**Comment by ks38** [comment]
действительно:)
сэкономили количество вычислений)
