### ISSUE TITLE
тот самый случай, когда...

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#11]
https://github.com/ks38/skillbox_python/blob/5bb44802382311674b79a85886d74e9242ad0edf/module_7/tasks/task_2.py#L13
for months in range(MONTHS_AMOUNT):
---
for _ in range(MONTHS_AMOUNT):

**Comment by ks38** [comment]
ага, переменная Чёчика не используется)
мерси:)
вроде понял)
