### ISSUE TITLE
Нужно поправить

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#2]
https://github.com/ks38/skillbox_python/blob/c3db15bd70406148ee3300394b419c405d6b9f5b/module_6/tasks/task_3.py#L19

В числе 0 есть одна цифра - это 0.
Случай, который выпадает из общего ряда.
Рекомендую до цикла сказать интерпретатору следующее:
если число равно нулю,
    то счетчик равен единице

**Comment by ks38** [comment]
> готовченко!

**Comment by jaggrenko** [comment]
Фи 50 / 50
