### ISSUE TITLE
Требуется уточнение

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#3]
https://github.com/ks38/skillbox_python/blob/c3db15bd70406148ee3300394b419c405d6b9f5b/module_6/tasks/task_4.py#L29
...# на ней пользователи могут ставить оценку приложению от −100 до 100,
а у вас, Вячеслав, как этот момент реализован? =))

**Comment by ks38** [comment]
сделяль, вроде)

**Comment by jaggrenko** [comment]
Зер гут, Вячеслав, зер гут! =)
