### ISSUE TITLE
Фи!

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#4]
https://github.com/ks38/skillbox_python/blob/c3db15bd70406148ee3300394b419c405d6b9f5b/module_6/tasks/task_5.py#L66
Упускаете, Вячеслав, суть задания. Максиму в течение часа может и 100 задач прилететь, поэтому каждый цикл мы вынуждены спрашивать, сколько многострадальный на себе потянет ближайший час =)
wife_calls += int(input("Wife is calling. Answer? (1- yes, 0 - no) ")) -- я специально изменил эту строку,
чтобы появилась еще одна по ее образу и подобию, но с количество задач.
А теперь самый главный вопрос: как изменится код при таком подходе?

**Comment by ks38** [comment]
ааааааааааааааааа
я понял.

готово!

**Comment by jaggrenko** [comment]
Добавил более питоничную запись неравенства =)
