### ISSUE TITLE
Эммм...

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#5]
https://github.com/ks38/skillbox_python/blob/c3db15bd70406148ee3300394b419c405d6b9f5b/module_6/tasks/task_7.py#L23
Почему бы сразу не начать с вопроса: ду, число кавирить!?
guess_count = ду, число каварить!?
Затем подумать по поводу положения строки ввода в цикле =)

**Comment by ks38** [comment]
может быть готово)

**Comment by jaggrenko** [comment]
Убираем ввод цикла вниз цикла, потому что первый ввод до цикла отработает при входе в цикл =)
А при вводе в конце цикла при таком раскладе, считай, запускам цикл как в первую итерацию
