### ISSUE TITLE
Неугадайка

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#6]
https://github.com/ks38/skillbox_python/blob/c3db15bd70406148ee3300394b419c405d6b9f5b/module_6/tasks/task_8.py#L20
Я загадал 100, а он не угадал. А по ТЗ я имею на это право. Что делать?

**Comment by ks38** [comment]
кажется, сделяль

**Comment by jaggrenko** [comment]
Wunderbar! Vielmals wunderbar!
