### ISSUE TITLE
Кель кощьмар!!!

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#7]
https://github.com/ks38/skillbox_python/blob/3e7752ba7b8284d98f0e047e112a0b40e64ba698/module_7/tasks/task_2.py#L15

Мы ведь знаем, что а.среднее от (5 + 4) будет 4.5?
Так вот. Примение оператор, который применили к выражению.
Вы будете удивлены результатом =))

**Comment by ks38** [comment]
Пятетысячекратно извиняюС, достопочтенный господин!
Бес попутал! Руки дрожали! Оно всё само! :)


поправлено.
