### ISSUE TITLE
Об чем поет нам ко(т)д?

### ISSUE THREAD

**Issue by jaggrenko** [ks38/skillbox_python#9]
https://github.com/ks38/skillbox_python/blob/3e7752ba7b8284d98f0e047e112a0b40e64ba698/module_7/tasks/task_6.py#L15
И как мне понять что значит выражение? Правая его часть.
Предлагаю быть последовательным и посчитать его до условий, дать соответствующее имя.

**Comment by ks38** [comment]
SIR! YES SIR!
Полностью согласен!
